### ISSUE TITLE
Make cronjobs work with sis

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/suoritustarkistin#224]
The cronjobs currently are working on the oodi-methods. These should work with sis as well.

- [x] Process general mooc-completions: https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/253
- [x] Tab for automated mooc-reports: https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/258
- [x] Elements of AI: https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/251
- [x] Elements of AI: Building AI https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/252
- [x] IsKorotus: https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/250
- [x] General mooc-course cronjobs: https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/254
- [x] New tab for sis-cronjobs: https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/257
- [x] Missing courses: https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/274
- [x] Missing course unit realisations; https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/275
