### ISSUE TITLE
At the end of August: Make sure everything works when Open Uni drops the AY-coded courses on 1.9.

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/suoritustarkistin#381]
- [x] https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/532
- [x] https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/536
- [x] https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/534
