### ISSUE TITLE
rehaul server info screen

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/suoritustarkistin#59]
DEPRECATED - service is no longer mainly about scripts

set https://toska.cs.helsinki.fi/suoritustarkistin/serverinfo to automatically update:
- [ ] server status
- [ ] server last restarted
- [ ] last run time for scripts
- [ ] next run time for scripts
- [ ] amount of rows reported to reijo (per script/total)
- [ ] last time reports downloaded from ooditool (ReijoWatch!)
- [ ] suotar reports available for download in ooditool
- [ ] other cool stuff
